// backend/src/domain/entities/trainer.entity.ts

import { Email } from '../valueObjects/email.valueObject';
import { TrainerErrorType } from '../enums/trainerErrorType.enum';
import { ICreateTrainerRequestDTO } from '../dtos/createTrainerRequest.dto';
import { AuthErrorType } from '../enums/authErrorType.enum';

// Interface for Certification as per Prisma schema
interface Certification {
  name: string; // String, non-optional
  issuer: string; // String, non-optional
  dateEarned: Date; // DateTime, non-optional
  filePath: string; // String, non-optional
}

// Interface for Client as per Prisma schema
interface Client {
  userId: string; // String @db.ObjectId, non-optional
  membershipId: string | null; // String? @db.ObjectId, optional
  startDate: Date; // DateTime, non-optional
  active: boolean; // Boolean, non-optional
}

// Interface for PaymentDetails as per Prisma schema
interface PaymentDetails {
  method: string | null; // String?, optional
  rate: number | null; // Float?, optional
  currency: string | null; // String?, optional
  paymentHistory: PaymentHistory[]; // PaymentHistory[], non-optional (can be empty)
  upiId: string | null; // String?, optional
  bankAccount: string | null; // String?, optional
  ifscCode: string | null; // String?, optional
}

// Interface for PaymentHistory as per Prisma schema
interface PaymentHistory {
  paymentId: string; // String @db.ObjectId, non-optional
  amount: number; // Float, non-optional
  date: Date; // DateTime, non-optional
  periodStart: Date | null; // DateTime?, optional
  periodEnd: Date | null; // DateTime?, optional
  clientCount: number | null; // Int?, optional
  hoursWorked: number | null; // Float?, optional
}

// Interface for Availability as per Prisma schema
interface Availability {
  day: string; // String, non-optional
  startTime: string; // String, non-optional
  endTime: string; // String, non-optional
}

// Interface for Ratings as per Prisma schema
interface Ratings {
  average: number | null; // Float? @default(0.0), optional
  count: number | null; // Int? @default(0), optional
  reviews: Review[]; // Review[], non-optional (can be empty)
}

// Interface for Review as per Prisma schema
interface Review {
  userId: string; // String @db.ObjectId, non-optional
  rating: number; // Int, non-optional
  comment: string | null; // String?, optional
  date: Date; // DateTime @default(now()), non-optional
}

// Interfaces for Booking and Payment to match Prisma relations
interface Booking {
  id: string; // String @db.ObjectId
  // Add other fields if needed
}

interface Payment {
  id: string; // String @db.ObjectId
  // Add other fields if needed
}

interface TrainerProps {
  id?: string; // Optional, auto-generated by Prisma
  name: string; // String, non-optional
  email: Email; // Matches String @unique via Email value object
  password: string; // String, non-optional
  role: string; // String, non-optional
  profilePic: string | null; // String?, optional
  isVerified: boolean; // Boolean @default(false), non-optional
  verifiedByAdmin: boolean; // Boolean @default(false), non-optional
  otp: string | null; // String?, optional
  otpExpires: Date | null; // DateTime?, optional
  refreshToken: string | null; // String?, optional
  personalDetails: any | null; // Json?, optional
  certifications: Certification[]; // Certification[], non-optional (can be empty)
  bio: string | null; // String?, optional
  specialties: string[]; // String[], non-optional (can be empty)
  experienceLevel: string | null; // String?, optional
  clients: Client[]; // Client[], non-optional (can be empty)
  paymentDetails: PaymentDetails | null; // PaymentDetails?, optional
  availability: Availability[]; // Availability[], non-optional (can be empty)
  gyms: string[]; // String[] @db.ObjectId, non-optional (can be empty)
  phone: string | null; // String?, optional
  ratings: Ratings | null; // Ratings?, optional
  bookings: Booking[]; // Booking[], relation, non-optional (can be empty)
  payments: Payment[]; // Payment[], relation, non-optional (can be empty)
  createdAt: Date; // DateTime @default(now()), non-optional
  updatedAt: Date; // DateTime @updatedAt, non-optional
}

export class Trainer {
  private _id?: string;
  private _name: string;
  private _email: Email;
  private _password: string;
  private _role: string;
  private _profilePic: string | null;
  private _isVerified: boolean;
  private _verifiedByAdmin: boolean;
  private _otp: string | null;
  private _otpExpires: Date | null;
  private _refreshToken: string | null;
  private _personalDetails: any | null;
  private _certifications: Certification[];
  private _bio: string | null;
  private _specialties: string[];
  private _experienceLevel: string | null;
  private _clients: Client[];
  private _paymentDetails: PaymentDetails | null;
  private _availability: Availability[];
  private _gyms: string[];
  private _phone: string | null;
  private _ratings: Ratings | null;
  private _bookings: Booking[];
  private _payments: Payment[];
  private _createdAt: Date;
  private _updatedAt: Date;

  static create(props: ICreateTrainerRequestDTO): Trainer {
    if (!props.name?.trim() || !/^[a-zA-Z\s]{2,}$/.test(props.name.trim())) {
      throw new Error(TrainerErrorType.InvalidName);
    }
    if (!props.password?.trim() || props.password.trim().length < 5) {
      throw new Error(TrainerErrorType.InvalidPassword);
    }
    if (!props.experienceLevel?.trim()) {
      throw new Error(TrainerErrorType.MissingExperienceLevel);
    }
    if (!props.specialties?.length) {
      throw new Error(TrainerErrorType.MissingSpecialties);
    }
    if (!props.bio?.trim() || props.bio.trim().length < 5) {
      throw new Error(TrainerErrorType.InvalidBio);
    }
    if (!props.certifications?.length) {
      throw new Error(TrainerErrorType.MissingCertifications);
    }
    props.certifications.forEach((cert, i) => {
      if (!cert.name?.trim()) throw new Error(`Certification ${i + 1}: ${TrainerErrorType.MissingCertificationName}`);
      if (!cert.issuer?.trim()) throw new Error(`Certification ${i + 1}: ${TrainerErrorType.MissingCertificationIssuer}`);
      if (!cert.dateEarned) throw new Error(`Certification ${i + 1}: ${TrainerErrorType.MissingCertificationDate}`);
      if (!cert.filePath) throw new Error(`Certification ${i + 1}: ${TrainerErrorType.MissingCertificationFile}`);
    });

    try {
      const email = new Email({ address: props.email });
      return new Trainer({
        name: props.name.trim(),
        email,
        password: props.password.trim(),
        role: 'trainer',
        specialties: props.specialties,
        experienceLevel: props.experienceLevel.trim(),
        bio: props.bio.trim(),
        certifications: props.certifications,
        isVerified: false,
        verifiedByAdmin: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        profilePic: null,
        personalDetails: null,
        clients: [],
        paymentDetails: null,
        availability: [],
        gyms: [],
        phone: null,
        ratings: null,
        bookings: [],
        payments: [],
        otp: null,
        otpExpires: null,
        refreshToken: null,
      });
    } catch (error) {
      throw new Error(TrainerErrorType.InvalidEmail);
    }
  }

  // Getters
  get id(): string | null {
    return this._id ?? null; // Return null if undefined to match Prisma
  }

  get name(): string {
    return this._name;
  }

  get email(): Email {
    return this._email;
  }

  get password(): string {
    return this._password;
  }

  get role(): string {
    return this._role;
  }

  get profilePic(): string | null {
    return this._profilePic;
  }

  get isVerified(): boolean {
    return this._isVerified;
  }

  get verifiedByAdmin(): boolean {
    return this._verifiedByAdmin;
  }

  get otp(): string | null {
    return this._otp;
  }

  get otpExpires(): Date | null {
    return this._otpExpires;
  }

  get refreshToken(): string | null {
    return this._refreshToken;
  }

  get personalDetails(): any | null {
    return this._personalDetails;
  }

  get certifications(): Certification[] {
    return this._certifications;
  }

  get bio(): string | null {
    return this._bio;
  }

  get specialties(): string[] {
    return this._specialties;
  }

  get experienceLevel(): string | null {
    return this._experienceLevel;
  }

  get clients(): Client[] {
    return this._clients;
  }

  get paymentDetails(): PaymentDetails | null {
    return this._paymentDetails;
  }

  get availability(): Availability[] {
    return this._availability;
  }

  get gyms(): string[] {
    return this._gyms;
  }

  get phone(): string | null {
    return this._phone;
  }

  get ratings(): Ratings | null {
    return this._ratings;
  }

  get bookings(): Booking[] {
    return this._bookings;
  }

  get payments(): Payment[] {
    return this._payments;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  // Methods
  updateOtp(otp: string, expires: Date): void {
    this._otp = otp;
    this._otpExpires = expires;
    this._updatedAt = new Date();
  }

  verify(): void {
    if (this._isVerified) {
      throw new Error(TrainerErrorType.AlreadyVerified);
    }
    if (this._otpExpires && this._otpExpires < new Date()) {
      throw new Error(AuthErrorType.OtpExpired);
    }
    this._isVerified = true;
    this._otp = null;
    this._otpExpires = null;
    this._updatedAt = new Date();
  }

  verifyByAdmin(): void {
    if (this._verifiedByAdmin) {
      throw new Error(TrainerErrorType.AlreadyVerifiedByAdmin);
    }
    this._verifiedByAdmin = true;
    this._updatedAt = new Date();
  }

  updateRefreshToken(token: string): void {
    this._refreshToken = token;
    this._updatedAt = new Date();
  }

   constructor(props: TrainerProps) {
    this._id = props.id;
    this._name = props.name;
    this._email = props.email;
    this._password = props.password;
    this._role = props.role;
    this._profilePic = props.profilePic ?? null;
    this._isVerified = props.isVerified ?? false;
    this._verifiedByAdmin = props.verifiedByAdmin ?? false;
    this._otp = props.otp ?? null;
    this._otpExpires = props.otpExpires ?? null;
    this._refreshToken = props.refreshToken ?? null;
    this._personalDetails = props.personalDetails ?? null;
    this._certifications = props.certifications ?? [];
    this._bio = props.bio ?? null;
    this._specialties = props.specialties ?? [];
    this._experienceLevel = props.experienceLevel ?? null;
    this._clients = props.clients ?? [];
    this._paymentDetails = props.paymentDetails ?? null;
    this._availability = props.availability ?? [];
    this._gyms = props.gyms ?? [];
    this._phone = props.phone ?? null;
    this._ratings = props.ratings ?? null;
    this._bookings = props.bookings ?? [];
    this._payments = props.payments ?? [];
    this._createdAt = props.createdAt ?? new Date();
    this._updatedAt = props.updatedAt ?? new Date();
  }
}