// backend/src/domain/entities/user.entity.ts

import { Email } from '../valueObjects/email.valueObject';
import { UserErrorType } from '../enums/userErrorType.enum';
import { ICreateUserRequestDTO } from '../dtos/createUserRequest.dto';
import { AuthErrorType } from '../enums/authErrorType.enum';

// Interface for FitnessProfile as per Prisma schema
interface FitnessProfile {
  goals: string[]; // String[] in Prisma, non-optional but empty array as default
  weight?: number; // Float? in Prisma, mapped to number | null
  height?: number; // Float? in Prisma, mapped to number | null
  level?: string; // String? in Prisma, mapped to string | null
  calorieGoal?: number; // Float? in Prisma, mapped to number | null
  updatedAt?: Date; // DateTime? in Prisma, mapped to Date | null
}

// Interface for Progress as per Prisma schema
interface Progress {
  workoutDate: Date; // DateTime in Prisma, non-optional
  planId: string; // String @db.ObjectId in Prisma, non-optional
  exercisesCompleted: ExerciseCompleted[]; // ExerciseCompleted[] in Prisma, non-optional but can be empty
  totalDuration?: number; // Float? in Prisma, mapped to number | null
  totalCaloriesBurned?: number; // Float? in Prisma, mapped to number | null
  dailyDifficulty?: string; // String? in Prisma, mapped to string | null
}

// Interface for ExerciseCompleted as per Prisma schema
interface ExerciseCompleted {
  exerciseId: string; // String @db.ObjectId in Prisma, non-optional
  name: string; // String in Prisma, non-optional
  sets?: number; // Int? in Prisma, mapped to number | null
  reps?: number; // Int? in Prisma, mapped to number | null
  weight?: number; // Float? in Prisma, mapped to number | null
  duration?: number; // Float? in Prisma, mapped to number | null
  difficulty?: string; // String? in Prisma, mapped to string | null
  caloriesBurned?: number; // Float? in Prisma, mapped to number | null
}

// Interface for WeeklySummary as per Prisma schema
interface WeeklySummary {
  weekStart: Date; // DateTime in Prisma, non-optional
  weekEnd: Date; // DateTime in Prisma, non-optional
  totalCaloriesBurned?: number; // Float? in Prisma, mapped to number | null
  weeklyDifficulty?: string; // String? in Prisma, mapped to string | null
}

// Interface for Membership, Booking, and Payment to match Prisma relations
interface Membership {
  id: string; // String @db.ObjectId in Prisma
  // Add other fields if needed for business logic
}

interface Booking {
  id: string; // String @db.ObjectId in Prisma
  // Add other fields if needed for business logic
}

interface Payment {
  id: string; // String @db.ObjectId in Prisma
  // Add other fields if needed for business logic
}

interface UserProps {
  id?: string; // Optional, as ID is generated by Prisma/MongoDB
  name: string; // String in Prisma, non-optional
  email: Email; // Custom value object, assumed to match Prisma's String @unique
  password: string; // String in Prisma, non-optional
  role: string; // String in Prisma, non-optional
  createdAt?: Date; // DateTime @default(now()) in Prisma, non-optional in DB but optional in props
  updatedAt?: Date; // DateTime @updatedAt in Prisma, non-optional in DB but optional in props
  otp?: string | null; // String? in Prisma, mapped to string | null
  otpExpires?: Date | null; // DateTime? in Prisma, mapped to Date | null
  isVerified?: boolean; // Boolean @default(false) in Prisma, non-optional in DB but optional in props
  refreshToken?: string | null; // String? in Prisma, mapped to string | null
  profilePic?: string | null; // String? in Prisma, mapped to string | null
  membershipId?: string | null; // String? @db.ObjectId in Prisma, mapped to string | null
  fitnessProfile?: FitnessProfile | null; // FitnessProfile? in Prisma, mapped to FitnessProfile | null
  workoutPlanId?: string | null; // String? @db.ObjectId in Prisma, mapped to string | null
  progress?: Progress[]; // Progress[] in Prisma, non-optional but can be empty array
  weeklySummary?: WeeklySummary[]; // WeeklySummary[] in Prisma, non-optional but can be empty array
  memberships?: Membership[]; // Membership[] in Prisma, relation to Membership model
  Bookings?: Booking[]; // Booking[] in Prisma, relation to Booking model
  payments?: Payment[]; // Payment[] in Prisma, relation to Payment model
}

export class User {
  private _id?: string;
  private _name: string; // Non-nullable, as per Prisma schema
  private _email: Email;
  private _password: string;
  private _role: string;
  private _createdAt: Date;
  private _updatedAt: Date;
  private _otp: string | null;
  private _otpExpires: Date | null;
  private _isVerified: boolean;
  private _refreshToken: string | null;
  private _profilePic: string | null;
  private _membershipId: string | null;
  private _fitnessProfile: FitnessProfile | null;
  private _workoutPlanId: string | null;
  private _progress: Progress[];
  private _weeklySummary: WeeklySummary[];
  private _memberships: Membership[];
  private _Bookings: Booking[];
  private _payments: Payment[];

  // Static method to create a new user
  static create({ name, email, password }: ICreateUserRequestDTO): User {
    if (!name || !email || !password) {
      throw new Error(UserErrorType.MissingRequiredFields);
    }

    try {
      const emailVO = new Email({ address: email });
      return new User({
        name,
        email: emailVO,
        password,
        role: 'user',
        createdAt: new Date(),
        updatedAt: new Date(),
        isVerified: false,
        otp: null,
        otpExpires: null,
        refreshToken: null,
        profilePic: null,
        membershipId: null,
        fitnessProfile: null,
        workoutPlanId: null,
        progress: [],
        weeklySummary: [],
        memberships: [],
        Bookings: [],
        payments: [],
      });
    } catch (error) {
      throw new Error(UserErrorType.InvalidCredentials);
    }
  }

  // Getters
  get id(): string | null {
    return this._id || null; // Return null if undefined to match Prisma
  }

  get name(): string {
    return this._name;
  }

  get email(): Email {
    return this._email;
  }

  get password(): string {
    return this._password;
  }

  get role(): string {
    return this._role;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  get otp(): string | null {
    return this._otp;
  }

  get otpExpires(): Date | null {
    return this._otpExpires;
  }

  get isVerified(): boolean {
    return this._isVerified;
  }

  get refreshToken(): string | null {
    return this._refreshToken;
  }

  get profilePic(): string | null {
    return this._profilePic;
  }

  get membershipId(): string | null {
    return this._membershipId;
  }

  get fitnessProfile(): FitnessProfile | null {
    return this._fitnessProfile;
  }

  get workoutPlanId(): string | null {
    return this._workoutPlanId;
  }

  get progress(): Progress[] {
    return this._progress;
  }

  get weeklySummary(): WeeklySummary[] {
    return this._weeklySummary;
  }

  get memberships(): Membership[] {
    return this._memberships;
  }

  get Bookings(): Booking[] {
    return this._Bookings;
  }

  get payments(): Payment[] {
    return this._payments;
  }

  // Methods to update OTP and verification status
  updateOtp(otp: string, expires: Date): void {
    this._otp = otp;
    this._otpExpires = expires;
    this._updatedAt = new Date();
  }

  verify(): void {
    if (this._isVerified) {
      throw new Error(UserErrorType.UserAlreadyVerified);
    }
    if (this._otpExpires && this._otpExpires < new Date()) {
      throw new Error(AuthErrorType.OtpExpired);
    }
    this._isVerified = true;
    this._otp = null;
    this._otpExpires = null;
    this._updatedAt = new Date();
  }

  updateRefreshToken(token: string): void {
    this._refreshToken = token;
    this._updatedAt = new Date();
  }

  constructor(props: UserProps) {
    this._id = props.id;
    this._name = props.name;
    this._email = props.email;
    this._password = props.password;
    this._role = props.role;
    this._createdAt = props.createdAt || new Date();
    this._updatedAt = props.updatedAt || new Date();
    this._otp = props.otp ?? null; // Use nullish coalescing to handle undefined
    this._otpExpires = props.otpExpires ?? null;
    this._isVerified = props.isVerified ?? false;
    this._refreshToken = props.refreshToken ?? null;
    this._profilePic = props.profilePic ?? null;
    this._membershipId = props.membershipId ?? null;
    this._fitnessProfile = props.fitnessProfile ?? null;
    this._workoutPlanId = props.workoutPlanId ?? null;
    this._progress = props.progress ?? [];
    this._weeklySummary = props.weeklySummary ?? [];
    this._memberships = props.memberships ?? [];
    this._Bookings = props.Bookings ?? [];
    this._payments = props.payments ?? [];
  }
}